# Generated by Django 6.0.2 on 2026-03-01 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('account_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FM_Customer_Segment',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('recency', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('monetary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('r_score', models.IntegerField()),
                ('f_score', models.IntegerField()),
                ('m_score', models.IntegerField()),
                ('rfm_score', models.IntegerField()),
                ('segment', models.CharField(max_length=100)),
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Forecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('forecast_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=15)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=15)),
                ('model_version', models.CharField(max_length=50)),
                ('mape', models.DecimalField(decimal_places=2, help_text='Mean Absolute Percentage Error', max_digits=5)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.customer')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.product')),
            ],
        ),
    ]
